specVersion: 0.2.0
name: parallel-lending-subql
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  endpoint: wss://parallel-heiko.api.onfinality.io/public-ws
  genesisHash: '0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b'
dataSources:
  - kind: substrate/Runtime
    startBlock: 118688
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: loans
        - handler: handleBlock
          kind: substrate/BlockHandler
