specVersion: 0.2.0
name: parallel-lending-subql
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  endpoint: wss://rpc.parallel.fi
  genesisHash: '0xe61a41c53f5dcd0beb09df93b34402aada44cb05117b71059cce40a2723a4e97'
  # endpoint: wss://testnet-parachain-rpc-v2.parallel.fi
  # genesisHash: '0x7582065adbd7e169615fdff1dd56071073a39f2232fac6030561855c4f989723'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: loans
        - handler: handleBlock
          kind: substrate/BlockHandler
